### ISSUE TITLE
能获取评论的人的地址吗

### ISSUE THREAD

**Issue by KaitaoQiu** [NewComer00/douyin-comment-picker#1]
我测试了下，非常好用，请问能获得评论的人的地址吗？我看似乎是在这一步获取所有的评论的，但是似乎没有评论的人的主页地址
```
        let commentMainContent = body.getElementsByClassName("comment-mainContent")[0];
```

**Comment by NewComer00** [comment]
感谢您的关注！你需要的是“获取评论者的个人主页链接”吗？我之前没有这个需求，所以没想到这个功能，我有空的时候学习一下。想要自己开发的话，欢迎fork！有什么问题也欢迎提问～

**Comment by NewComer00** [comment]
https://stackoverflow.com/questions/10730309/find-all-text-nodes-in-html-page/10730777#10730777

这个函数只能获取节点中的文本，比如两个span标签之间的文本；应该不能获取节点的属性，比如href=后面的链接

**Comment by NewComer00** [comment]
您好！我的QQ是1280581103，欢迎联系

**Comment by NewComer00** [comment]
已经添加了该特性，可以前往PR #4查看。确认功能正常后我会合并#4

**Comment by KaitaoQiu** [comment]
> 已经添加了该特性，可以前往PR #4查看。确认功能正常后我会合并#4

全是你自己些的，你开源干嘛呢？？

**Comment by KaitaoQiu** [comment]
> #2 提交PR了，你能review一下吗？谢谢

如果你觉得别人的工作不重要，你直接写上去，不接受其他人pr
