### ISSUE TITLE
[bug] 图文的时候会有卡住

### ISSUE THREAD

**Issue by KaitaoQiu** [NewComer00/douyin-comment-picker#3]
抖索到抖音图文显示的时候会有bug，一直卡住，视频的时候没有问题

**Comment by NewComer00** [comment]
https://github.com/NewComer00/douyin-comment-picker/blob/891c7c99fa9c96be5b4eee41ec4a5b0ef5500cb6/douyin.js#LL367C1-L371C1

这里的逻辑是：在状态二（处理每个编号的视频）时，会首先检测“当前浏览的网址”是否为“要处理的视频网址”。如果是，则无事发生继续处理；如果不是，则跳转到“要处理的视频网址”。

跳转后的新网址，即“要处理的视频网址”，由videoUrl变量控制，网址格式为`'https://%s/video/%s'`。

请给一个例子让我复现一下。提供“视频关键词”、“评论筛选关键词”和“最大浏览视频数量”。

**Comment by NewComer00** [comment]
我明白你的意思。脚本在一开始搜索视频时，会限制搜索结果类别为“视频”，应当不会搜索到“图文”才对。

我在插件中输入搜索关键词“帝国理工学院申请|学习”，插件搜索的结果全是视频，不会搜索到图文。

https://github.com/NewComer00/douyin-comment-picker/blob/891c7c99fa9c96be5b4eee41ec4a5b0ef5500cb6/douyin.js#L291

**Comment by NewComer00** [comment]
看到了，抖音真是骚操作不断啊。。。
如果要兼容图文的话，我想这么改：

```
            if (videoIdArr !== null && !isNaN(videoCurIndex)) {
                // 如果当前页面不在正确的地址，跳转至准备处理的视频地址
                const videoUrl = strFormat('https://%s/video/%s', DOMAIN, videoIdArr[videoCurIndex]);
                // 抖音的图文笔记可能会伪装成视频，我们也兼容搜索图文笔记
                const noteUrl = strFormat('https://%s/note/%s', DOMAIN, videoIdArr[videoCurIndex]);
                if (window.location.href !== videoUrl && window.location.href !== noteUrl) {
                    window.location.href = videoUrl;
                }
```

**Comment by NewComer00** [comment]
新版本[0.5.2](https://greasyfork.org/zh-CN/scripts/452032-%E6%8A%96%E9%9F%B3%E8%AF%84%E8%AE%BA%E7%AD%9B%E9%80%89%E5%99%A8-douyin-comment-picker)已经发布，本地测试暂时没有遇到问题。
## 测试环境
Microsoft Edge Version 112.0.1722.58 (Official build) (64-bit)

## 测试步骤
1. 更新脚本后打开抖音网站。
2. 输入任意搜索主题。输入评论关键词`私房钱 红小豆`。输入任意视频数量。
3. 在油猴中此脚本的第340行下，手动加入两个测试图文笔记编号`videoIdArr = ['7223655518441639227', '7205818352021802272'];`。
https://github.com/NewComer00/douyin-comment-picker/blob/32854d9d2cec3526ee3745d86aeae3ed27d4a55a/douyin.js#L338-L342
5. 在油猴脚本界面按下`Ctrl + S`保存修改。
6. 点击`开始筛选评论`按钮。

## 理想结果
应当能搜索到含关键词的评论。
